name: CI

on: push

defaults:
    run:
        shell: bash

jobs:
    build:

        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
                build_type: [Debug, Release]
                include:
                    - os: ubuntu-latest
                      conan-cxx-version: libstdc++11
                    - os: macos-latest
                      conan-cxx-version: libc++

        name: Build Babel
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2

            - name: Install Required Dependencies on Ubuntu
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: |
                sudo apt update
                sudo apt install -y libgl-dev g++-11
                sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 --slave /usr/bin/g++ g++ /usr/bin/g++-11

            - name: Create Build Directories
              run: |
                mkdir build
                mkdir build-tests

            - name: Generate Project Build Files
              working-directory: build
              run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

            - name: Build Project
              working-directory: build
              run: cmake --build .

            - name: Build Unit Tests
              working-directory: build-tests
              run: |
                cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON
                cmake --build .

            - name: Run Unit Tests
              run: ./TheZapTests