name: Action

on: [push, pull_request]

defaults:
    run:
        shell: bash

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
              os: [windows-latest, ubuntu-latest, macos-latest]
              build_type: [Debug, Release]
              include:
              - os: windows-latest
                bin: TheZapTests.exe
                dir: Debug
              - os: ubuntu-latest
                bin: TheZapTests
                dir: .
              - os: macos-latest
                bin: TheZapTests
                dir: .

        name: CI
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2

            - name: Install Required Dependencies on Ubuntu
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: |
                sudo apt update
                sudo apt install -y libgl-dev g++-11
                sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 --slave /usr/bin/g++ g++ /usr/bin/g++-11

            - name: Build Project
              run: make

            - name: Build Unit Tests
              run: make tests

            - name: Run Unit Tests
              working-directory: ${{ matrix.dir }}
              run: ./${{ matrix.bin }}